# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensoresClaro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monnit_ID', models.CharField(max_length=20)),
                ('Device_ID', models.CharField(max_length=20)),
                ('Autorizacion', models.CharField(max_length=300)),
                ('Tipo', models.CharField(choices=[('Temperatura/Humedad', 'Temperatura/Humedad'), ('Movimiento', 'Movimiento'), ('Detector Voltaje', 'Detector Voltaje'), ('Medidor Voltaje', 'Medidor Voltaje'), ('Corriente Trifasica', 'Corriente Trifasica'), ('Detector Puerta', 'Detector Puerta'), ('Ultrasonico', 'Ultrasonico'), ('Gateway', 'Gateway')], max_length=50)),
            ],
        ),
    ]
